Yearly_projects/yearly_7_sem/ads/config/routes.rb
Ads::Application.routes.draw do

  root :to => 'ads#index'

  get '/help', to: 'static_pages#help'

  resources :ads do
    resources :comments, :only => :create
    put 'change_state', :on => :member
  end

  resources :comments, :only => :destroy

  devise_for :users, :controllers => { :users => "users",
      :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users, only: [:index, :destroy, :show] do
    put 'make_admin', :on => :member

    resources :announcements, only: :index do
      delete 'clear', :on => :collection
    end

  end

  resources :announcements, only: :destroy

  resources :ad_types, only: [:create, :destroy, :new]
  resources :places, only: [:create, :destroy, :new]
  resources :currencies, only: [:create, :destroy, :new]

  resources :sections, only: [:create, :destroy, :new] do
    resources :subsections, only: [:create, :new]
  end
  resources :subsections, only: [:destroy]


end

Yearly_projects/yearly_7_sem/ads/app/models/ad.rb
class Ad < ActiveRecord::Base

  attr_accessible :content, :photos_attributes, :ad_type_id, :place_id, :subsection_id, :currency_id, :price

  belongs_to :user
  belongs_to :ad_type
  belongs_to :place
  belongs_to :subsection
  belongs_to :currency

  has_many :photos, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :announcements, :dependent => :destroy
  has_and_belongs_to_many :keywords

  validates :user_id, :ad_type_id, :place_id, :subsection_id,
    :currency_id, presence: true
  validates :content, presence: true, length: {maximum: 200}, format: { with: GlobalConstants::Content_regexp }

  accepts_nested_attributes_for :photos, :allow_destroy => true

  default_scope order: 'ads.created_at DESC'

  scope :published, -> { where(state: 'published') }
  scope :posting, -> { where(state: 'posting') }

  @@Per_page_small = 5
  @@Per_page_big = 12
  @@max_price = 2 ** (1.size * 8 - 1)


  def self.max_price
    @@max_price
  end
  def self.per_page_small
    @@Per_page_small
  end
  def self.per_page_big
    @@Per_page_big
  end

  validates_numericality_of :price, greater_than_or_equal_to: 0,
    less_than: max_price, :allow_nil => true,
    :message => "can only be ranged number"

  state_machine :state, :initial => :drafting do

    after_transition :approved => :published do |ad, transition|
      ad.published_at = Time.now
      ad.save
    end

    after_transition :published => :archived do |ad, transition|
      ad.published_at = nil
      ad.save
      new_announcement(ad, transition)
    end

    after_transition :posting => any do |ad, transition|
      new_announcement(ad, transition)
    end

    after_transition any => [:published, :archived] do |ad, transition|
      new_announcement(ad, transition)
    end

    event :post do
      transition :drafting => :posting
    end

    event :reject do
      transition :posting => :rejected
    end

    event :approve do
      transition :posting => :approved
    end

    event :publish do
      transition :approved => :published
    end

    event :archive do
      transition :published => :archived
    end

    event :draft do
      transition [:rejected, :archived] => :drafting
    end

    def new_announcement(ad, transition)
      an = ad.user.announcements.build(ad_id: ad.id,
        content: I18n.translate(:was, scope: [:ads]) + transition.to);
      an.save
    end
  end

end

Yearly_projects/yearly_7_sem/ads/app/models/ad_type.rb
class AdType < ActiveRecord::Base
  include Option

  attr_accessible :name
  has_many :ads
  validates :name, presence: true,
    format: { with: GlobalConstants::Content_regexp}, length: {maximum: 20}
  before_destroy :before_destroy

end

Yearly_projects/yearly_7_sem/ads/app/controllers/ads_controller.rb
class AdsController < ApplicationController
  load_and_authorize_resource

  def create

    @ad.keywords = get_keywords_from_params
    current_user.ads << @ad
    @ad.save
    load_dropdown_collections
    load_keywords_and_hints
    respond_with(@ad, :location => @ad)

  end

  def destroy
    @ad.destroy
    respond_with @ad
  end

  def index

    ad_type_id = params['ad_type_id'].blank? ? nil : params['ad_type_id']
    order = params['created_at'] || 'created_at DESC'
    @ads = Ad.search(params['key_word'],
      :sql => {:include => [:user, :ad_type, :photos] },
      :conditions => {:ad_type_id => ad_type_id, :state => :published},
      :order => order, :page => params[:page], :per_page => Ad.per_page_small)
    @ad_types = AdType.all

  end

  def update

    @ad.keywords = get_keywords_from_params
    @ad.attributes = params[:ad]
    @ad.save
    load_dropdown_collections
    load_keywords_and_hints
    respond_with(@ad, :location => @ad)

  end

  def show

    load_keywords
    session[:return_to] ||= request.referer
    @ad_types = AdType.all

    if can? :create, Comment
      @comment = current_user.comments.build(params[:comment])
      @comment.ad_id = params[:id]
    end

  end

  def edit
    load_dropdown_collections
    load_keywords_and_hints
  end

  def new
    load_dropdown_collections
    load_keywords_hint
  end

  def change_state

    @ad.public_send(params[:state_event])
    @ad.save
    flash[:notice] = t(:status_changed, scope: [:ads])
    redirect_to(:back)

  end

  private

  def load_keywords_and_hints
    load_keywords
    load_keywords_hint
  end

  def load_keywords
    gon.watch.keywords = @ad.keywords
  end

  def load_keywords_hint
    gon.keywords_hint = Keyword.all
  end

  def get_keywords_from_params

    if params['tags']
      params['tags'].split(',').
        map { |keyword| Keyword.find_or_create_by_name(keyword) }
    else
      return []
    end

  end

  def load_dropdown_collections

    @ad_types = AdType.all
    @places = Place.all
    @sections = Section.all
    @currencies = Currency.all

  end

end

Yearly_projects/yearly_7_sem/ads/app/views/ads/_ad.html.haml
= render 'ads/ad_main', :ad => ad
= render 'ads/info', :ad => ad

Yearly_projects/yearly_7_sem/ads/app/views/ads/_ad_main.html.haml
%li
  %span.cont= link_to ad.content, ad
  %br/
  %span.photos
    = render_gallery_for ad.photos,                                   |
      original: 'image_full', thumbnail: 'image_thumb', title: 'name' |
  .info
    .ad_type
      = ad.ad_type.name
      | #{ad.place.name}
      | #{ad.subsection.section.name}
      \- #{ad.subsection.name}
    = ad.state
    by #{link_to ad.user.name, ad.user}
    %br/
  - if ad.price
    = ad.price
    = ad.currency.name

Yearly_projects/yearly_7_sem/ads/app/views/ads/_ads.html.haml
%ul.models
  = render :partial => 'ads/ad', :collection => @ads, :as => :ad
  = will_paginate @ads
  - if (@ads.blank?)
    %p No ad available...

Yearly_projects/yearly_7_sem/ads/app/views/ads/_form.html.haml
= simple_nested_form_for @ad do |f|

  = f.input :content, required: true, :class => 'info'

  = label_tag :keywords

  %ul.writable#keywords
  %br

  = collection_select(:ad, :ad_type_id, @ad_types,         |
    :id, :name, {}, { :class => 'selectpicker show-tick'})

  = collection_select(:ad, :place_id, @places,             |
    :id, :name, {}, { :class => 'selectpicker show-tick'})

  %br/
  = grouped_collection_select(:ad, :subsection_id, @sections, :subsections, :name,
    :id, :name, {}, { :class => 'selectpicker show-tick', 'data-live-search' => "true"})

  = f.input :price, error: false, input_html: { min: 0, max: Ad.max_price }
  = collection_select(:ad, :currency_id, @currencies, |
    :id, :name)
  .control-group.error
    = f.error :price

  = f.fields_for :photos, :html => { :multipart => true} do |photo_form|
    = photo_form.file_field :file, :accept => 'image/*'
    %br/
    = photo_form.text_field :name,          |
      placeholder: 'Enter name of photo...' |
    = photo_form.link_to_remove 'Remove this photo'
  %p= f.link_to_add 'Add photo', :photos

  = f.submit 'Ok', :class => 'zocial'

Yearly_projects/yearly_7_sem/ads/app/views/ads/_info.html.haml
.info
  - if (ad.comments.count != 0)
    = ad.comments.count
    = 'comment'.pluralize(ad.comments.count)

Yearly_projects/yearly_7_sem/ads/app/views/ads/_links.html.haml
- if can? :destroy, ad
  = link_to 'delete', ad, method: :delete, |
    data: { confirm: 'You  sure?' },       |
    title: ad.content                      |
  %br/
- if ((can? :update, ad) && ad.drafting?)
  = link_to 'edit', edit_ad_path(ad)
  %br/
- if can? :change_state, ad
  - ad.state_transitions.each do |transition|
    = link_to transition.event, { :controller => 'ads', :action => 'change_state',
      :id => ad, :state_event => transition.event }, :method => :put
    %br/

Yearly_projects/yearly_7_sem/ads/app/views/ads/edit.html.haml
%h3 Ad editing
= render 'form'

Yearly_projects/yearly_7_sem/ads/app/views/ads/index.html.haml
= form_tag ads_path, :method => :get, :remote => true do
  = select_tag :ad_type_id,                                   |
    options_for_select([['All ads', '']]) +                   |
    options_from_collection_for_select(@ad_types, :id, :name, |
    params[:ad_type_id].to_i)

  = select_tag :created_at,                                  |
    options_for_select([['Newer first', 'created_at DESC'],  |
    ['Older first', 'created_at ASC']], params[:created_at]) |

  %br/
  = text_field_tag :key_word, params[:key_word], |
    :placeholder => 'key words...'                   |

  %br/
  = submit_tag :search, :class => 'zocial'
  = link_to 'reset', '#',  :onclick => "reset()"

#ads
  = render 'ads'

Yearly_projects/yearly_7_sem/ads/app/views/ads/index.js.haml
$("#ads").html("#{j render('ads')}");

Yearly_projects/yearly_7_sem/ads/app/views/ads/new.html.haml
%h3 Ad creation
= render 'form'

Yearly_projects/yearly_7_sem/ads/app/views/ads/show.html.haml
%table
  %tr

    %td
      = render 'ad_main', :ad => @ad
      - if !@ad.keywords.blank?
        .small-font Keywords:
        %ul.readOnly#keywords.no-border

    %td.right
      = render 'ads/links', :ad => @ad

= render 'comments/comments', :comments => @ad.comments
- if can? :create, Comment
  = render 'comments/new_form'